# References: 
# https://stackoverflow.com/a/75308228
# https://michaelcurrin.github.io/dev-cheatsheets/cheatsheets/ci-cd/github-actions/persist.html

# This workflow is triggered on push to the main branch
# This workflow is commiting the sha vaersion to the deployment repo 
# which will further take the deployment using the argo workflow

# yaml-language-server: $schema='none'


name: Build test and deploy

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    outputs:
      GIT_SHA: ${{ steps.git_sha.outputs.GIT_SHA }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm ci  # Replace with your dependency installation command
        working-directory: backend

      - name: Run tests
        run: npm test  # Replace with your test command
        working-directory: backend

      - name: Generate Git SHA
        id: git_sha
        run: | 
          echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        run: docker login -u kaushikkishore -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        working-directory: backend
        run: |
          docker build -t kaushikkishore/astuto-web-app:${{ steps.git_sha.outputs.GIT_SHA }} .
          docker tag kaushikkishore/astuto-web-app:${{ steps.git_sha.outputs.GIT_SHA }} kaushikkishore/astuto-web-app:latest

      - name: Push Docker image
        run: |
          docker push kaushikkishore/astuto-web-app:${{ steps.git_sha.outputs.GIT_SHA }}
          docker push kaushikkishore/astuto-web-app:latest

  update-deployment: 
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout Deployment code
        uses: actions/checkout@v4
        with: 
          repository: kaushikkishore/k8s-deployment
          ref: main
          token: ${{ secrets.ACTIONS_ACCESS_TOKEN }} # confgiured for 3 months
    
      - name: Update Deployment YAML
        run: |
          sed -i '/image:/s/:.*/: kaushikkishore\/astuto-web-app:${{ needs.build-and-test.outputs.GIT_SHA }}/' astuto-web-app/deployment.yaml

      - name: Commit and Push
        run: |
          git config user.email "kk12391@gmail.com"
          git config user.name "kaushikkishore"
          git add astuto-web-app/deployment.yaml
          git commit -m "Update Docker image in deployment to Git SHA: ${{ needs.build-and-test.outputs.GIT_SHA }}"
          git push origin main

      
