name: Build test and deploy

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

permissions:
  contents: write
  repository-projects: write

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    outputs:
      GIT_SHA: ${{ steps.git_sha.outputs.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18  # Adjust the Node.js version as needed

      # - name: Install dependencies
      #   run: npm ci  # Replace with your dependency installation command
      #   working-directory: backend

      # - name: Run tests
      #   run: npm test  # Replace with your test command
      #   working-directory: backend

      - name: Generate Git SHA
        id: git_sha
        run: | 
          git_sha=$(git rev-parse --short HEAD)
          echo "::set-output name=sha::$(git rev-parse --short HEAD)"
          echo "$(git rev-parse --short HEAD)"
          echo "GIT_SHA=$git_sha" >> "$GITHUB_ENV"
          echo $GITHUB_ENV
      # - name: Login to Docker Hub
      #   run: docker login -u kaushikkishore -p ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build Docker image
      #   working-directory: backend
      #   run: |
      #     docker build -t kaushikkishore/astuto-web-app:${{ steps.git_sha.outputs.sha }} .
      #     docker tag kaushikkishore/astuto-web-app:${{ steps.git_sha.outputs.sha }} kaushikkishore/astuto-web-app:latest

      # - name: Push Docker image
      #   run: |
      #     docker push kaushikkishore/astuto-web-app:${{ steps.git_sha.outputs.sha }}
      #     docker push kaushikkishore/astuto-web-app:latest
  Deployment: 
    runs-on: ubuntu-latest
    needs: build-test-and-deploy

    steps:
      
      - name: Configure Git
        run: |
          gh auth login --with-token <<<"${{ secrets.GITHUB_TOKEN }}"

      - name: Checkout Kubernetes code
        uses: actions/checkout@v4
        with: 
          repository: kaushikkishore/k8s-deployment
          ref: main
          token: ${{ secrets.ACTIONS_ACCESS_TOKEN }}

      - name: Debug Outputs
        run: | 
          echo "Outputs: ${{ toJson(needs.build-test-and-deploy.outputs) }} sha ${{ needs.build-test-and-deploy.outputs.GIT_SHA }}"
        
      - name: Update Deployment YAML
        run: |
          ls -al
          sed -i '/image:/s/:.*/: kaushikkishore\/astuto-web-app:${{ needs.build-test-and-deploy.outputs.GIT_SHA }}/' astuto-web-app/deployment.yaml

      - name: Commit and Push
        run: |
          git config user.email "kk12391@gmail.com"
          git config user.name "kaushikkishore"
          git add astuto-web-app/deployment.yaml
          git commit -m "Update Docker image in deployment to Git SHA: ${{ needs.build-test-and-deploy.outputs.GIT_SHA }}"
          git push origin main

      
